### Create model
POST http://localhost:3000/models
content-type: application/json
api-key: fi8PE9AZJ38tjbSeRJAhlnOsw7P0A0W8Dazaz1ommpoaq36z

{
    "name": "Blog Post",
    "slug": "blog_post",
    "fields": [
        {
            "name": "Title",
            "slug": "title",
            "kind": "Text",
            "options": {
                "Text": {
                    "min_length": 1,
                    "max_length": 50
                }
            }
        },
        {
            "name": "Date",
            "slug": "date",
            "kind": "DateTime",
            "options": {
                "DateTime": {
                    "not_before": "2020-01-01T00:00:00.00Z",
                    "not_after": "2030-01-01T00:00:00.00Z"
                }
            }
        },
        {
            "name": "Body",
            "slug": "body",
            "kind": "Text"
        },
        {
            "name": "Draft?",
            "slug": "draft",
            "kind": "Boolean"
        },
        {
            "name": "Tags",
            "slug": "tags",
            "kind": {
                "Enum": [
                    "product",
                    "engineering",
                    "culture",
                    "marketing"
                ]
            },
            "options": {
                "Enum": {
                    "allow_multiple": true
                }
            }
        },
        {
            "name": "Number Field",
            "slug": "number",
            "kind": "Number",
            "options": {
                "Number": {
                    "min": 1,
                    "max": 69420
                }
            }
        }
    ]
}

### List models
GET http://localhost:3000/models
api-key: fi8PE9AZJ38tjbSeRJAhlnOsw7P0A0W8Dazaz1ommpoaq36z

### Show model
GET http://localhost:3000/models/blog_post
api-key: fi8PE9AZJ38tjbSeRJAhlnOsw7P0A0W8Dazaz1ommpoaq36z

### Create entry
POST http://localhost:3000/models/blog_post/entries
content-type: application/json
api-key: fi8PE9AZJ38tjbSeRJAhlnOsw7P0A0W8Dazaz1ommpoaq36z

{
    "fields": {
        "title": {
            "Text": "Simply the best CMS, hugely amazing."
        },
        "date": {
            "DateTime": "2023-10-16T12:00:00.00Z"
        },
        "body": {
            "Text": "It's written in Rust so it must be good!"
        },
        "draft": {
            "Boolean": false
        },
        "tags": {
            "Enum": [
                "product",
                "engineering"
            ]
        },
        "number": {
            "Number": 42
        }
    }
}

### List entries
GET http://localhost:3000/models/blog_post/entries
api-key: fi8PE9AZJ38tjbSeRJAhlnOsw7P0A0W8Dazaz1ommpoaq36z

### Get entry by id
GET http://localhost:3000/models/blog_post/entries?id=652b7e272560d5ac842c424c
api-key: fi8PE9AZJ38tjbSeRJAhlnOsw7P0A0W8Dazaz1ommpoaq36z

### Get serveral entries by id
GET http://localhost:3000/models/blog_post/entries?id=652b7e272560d5ac842c424c,652c1a4153b4cca62488ada5
api-key: fi8PE9AZJ38tjbSeRJAhlnOsw7P0A0W8Dazaz1ommpoaq36z

### Get entry by id with selection
GET http://localhost:3000/models/blog_post/entries?id=652b7e272560d5ac842c424c&select=title,date,tags
api-key: fi8PE9AZJ38tjbSeRJAhlnOsw7P0A0W8Dazaz1ommpoaq36z